# Generated by Django 4.2.6 on 2023-10-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deparetment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=200)),
                ('dep_discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Docter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200)),
                ('doc_spec', models.CharField(max_length=200)),
                ('doc_image', models.ImageField(blank=True, upload_to='docters')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deparetment')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_phone', models.CharField(max_length=200)),
                ('booking_date', models.DateField()),
                ('bookedon', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.docter')),
            ],
        ),
    ]
